/** Shared values, so colours and spacing are not repeated magic numbers across components. */
export const t = {
  bg: '#101216',
  card: '#1f2229',
  line: 'rgba(255,255,255,.08)',
  text: '#e5e7eb',
  muted: '#6b7280',
  accent: '#4250af',
  danger: '#f87171',
  radius: 18,
} as const;

export const s = {
  card: {
    background: t.card,
    border: `1px solid ${t.line}`,
    borderRadius: t.radius,
    padding: 18,
    margin: '14px 0',
  },
  row: { display: 'flex', justifyContent: 'space-between', alignItems: 'center', gap: 12 },
  item: { padding: '9px 0', borderBottom: `1px solid rgba(255,255,255,.06)`, fontSize: 14 },
  muted: { color: t.muted, fontSize: 13 },
  sub: { color: t.muted, fontSize: 12 },
  input: {
    flex: 1,
    font: 'inherit',
    fontSize: 14,
    padding: '10px 12px',
    borderRadius: 11,
    border: `1px solid rgba(255,255,255,.12)`,
    background: '#15171c',
    color: 'inherit',
    outline: 'none',
    width: '100%',
  },
  button: {
    font: 'inherit',
    fontSize: 14,
    fontWeight: 600,
    padding: '10px 18px',
    border: 0,
    borderRadius: 11,
    background: t.accent,
    color: '#fff',
    cursor: 'pointer',
  },
  danger: {
    background: 'transparent',
    border: `1px solid rgba(248,113,113,.45)`,
    color: t.danger,
    padding: '5px 12px',
    fontSize: 12,
    borderRadius: 11,
    cursor: 'pointer',
  },
  note: { fontSize: 13, marginTop: 10, color: '#8b9cf9', minHeight: 18 },
} as const;
